(function(){'use strict';
  var root='/api/runtime/control'; var state={key:sessionStorage.getItem('ronor.control.key')||'',overview:null};
  function el(id){return document.getElementById(id)}
  function node(tag,text,cls){var n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
  async function api(path,options){var headers={'Authorization':'Bearer '+state.key,'Content-Type':'application/json'};var response=await fetch(root+path,Object.assign({},options||{},{headers:headers}));var body=await response.json().catch(function(){return{ok:false,error:'invalid_response'}});if(!response.ok)throw new Error(body.message||body.error||('HTTP '+response.status));return body}
  function card(title,detail,status){var n=node('article','', 'card');n.append(node('b',title),node('span',detail));if(status)n.append(node('span',status,'status'));return n}
  function show(name){document.querySelectorAll('.view').forEach(function(v){v.classList.toggle('active',v.id===name)});document.querySelectorAll('nav button').forEach(function(b){b.classList.toggle('active',b.dataset.view===name)})}
  function renderOverview(data){var box=el('metrics');box.replaceChildren();[['Misiuni',data.missions.total],['Active',data.missions.active],['Fabric verificat',data.fabric.verified],['Integritate eșuată',data.fabric.failed],['Consiliu AI',data.council.members]].forEach(function(m){var n=node('article','', 'metric');n.append(node('strong',String(m[1])),node('span',m[0]));box.append(n)});var auto=el('automation');auto.replaceChildren();Object.keys(data.automation.adapters).forEach(function(k){auto.append(card(k.toUpperCase(),'Adapter de execuție',data.automation.adapters[k]))});auto.append(card('RUNNER','Politică deny-by-default',data.automation.runner));var missions=el('missionList');missions.replaceChildren();data.missions.recent.forEach(function(m){missions.append(card(m.title,m.mission_id,m.status))})}
  async function refresh(){try{await api('/session');el('sessionState').textContent='VERIFICAT';state.overview=(await api('/overview'));renderOverview(state.overview);var council=await api('/council');var grid=el('councilGrid');grid.replaceChildren();council.management.forEach(function(a){grid.append(card(a.name,a.role,a.email_status+' · '+a.email))});var models=await api('/models');var modelGrid=el('modelGrid');modelGrid.replaceChildren();models.cabinet.forEach(function(m){modelGrid.append(card(m.role,m.model+' · '+m.location,m.status+' · '+m.mode))})}catch(err){el('sessionState').textContent='ACCES RESPINS';el('result').textContent=err.message}}
  el('connect').addEventListener('click',function(){state.key=el('apiKey').value.trim();sessionStorage.setItem('ronor.control.key',state.key);refresh()});
  el('forget').addEventListener('click',function(){state.key='';sessionStorage.removeItem('ronor.control.key');el('apiKey').value='';el('sessionState').textContent='NEAUTENTIFICAT'});
  el('refresh').addEventListener('click',refresh);document.querySelectorAll('nav button').forEach(function(b){b.addEventListener('click',function(){show(b.dataset.view)})});
  el('delegateForm').addEventListener('submit',async function(ev){ev.preventDefault();var target=el('target').value,mode=el('mode').value;if(target!=='richard'||mode!=='delegate'){el('result').textContent='Înregistrare neexecutată: '+target+' nu are încă un adapter live conectat. Nicio acțiune nu a fost simulată.';return}try{var data=await api('/executive/delegate',{method:'POST',body:JSON.stringify({objective:el('objective').value})});el('result').textContent='MANDAT CREAT\nMisiune: '+data.delegation.mission_id+'\nStatus: draft · fără trimitere externă';await refresh()}catch(err){el('result').textContent='EROARE: '+err.message}});
  document.addEventListener('keydown',function(ev){if(ev.ctrlKey&&ev.key.toLowerCase()==='k'){ev.preventDefault();show('switchboard');el('objective').focus()}if(ev.key==='Escape')el('objective').blur()});
  if(state.key){el('apiKey').value=state.key;refresh()}
})();
